name: Login to GCR
description: Login to the GitHub Container Registry
inputs:
    username:
        description: The username of the account to authenticate with
        required: true
    password:
        description: The password of the account to authenticate with
        required: true
runs:
    using: composite
    steps:
        - name: Login to GCR
          uses: docker/login-action@v3
          with:
              registry: ghcr.io
              username: ${{ inputs.username }}
              password: ${{ inputs.password }}
