name: Build
permissions:
    contents: read
on:
    pull_request:
    push:
        branches:
            - main
jobs:
    execute:
        name: Execute
        uses: dnd-mapp/actions/.github/workflows/build.yml@main
        secrets:
            DATABASE_URL: ${{ secrets.DATABASE_URL }}
            COOKIE_SIGNING_SECRET: ${{ secrets.COOKIE_SIGNING_SECRET }}
            ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
            EMAIL_USER: ${{ secrets.EMAIL_USER }}
            EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
