name: CI
permissions:
    contents: read
on:
    pull_request:
    push:
        branches:
            - main
jobs:
    ci:
        name: CI
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: ./.github/actions/setup-node

            - name: Set main branch ref
              if: github.ref != 'refs/heads/main'
              run: git rev-parse --verify main || git remote set-branches origin main && git fetch --depth 1 origin main && git branch main origin/main

            - name: Check linting
              run: npx nx affected -t lint

            - name: Check formatting
              run: npx nx format:check

            - name: Compile code
              run: npx nx affected -t build

            - name: Run tests
              run: |
                  npx playwright install chromium
                  npx nx affected -t test
