name: CI
permissions:
    contents: read
on:
    pull_request:
    push:
        branches:
            - main
env:
    COOKIE_SIGNING_SECRET: ${{ secrets.COOKIE_SIGNING_SECRET }}
    DATABASE_URL: ${{ secrets.DATABASE_URL }}
    EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
    EMAIL_USER: ${{ secrets.EMAIL_USER }}
    ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
jobs:
    ci:
        name: CI
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Set up Node.js
              uses: ./.github/actions/setup-node
            - name: Check linting
              run: npx nx affected -t lint
            - name: Check formatting
              run: npx nx format:check
            - name: Compile code
              run: npx nx affected -t build
            - name: Run tests
              run: npx nx affected -t test
