name: Push to main
on:
    push:
        branches:
            - main
permissions:
    contents: read
jobs:
    ci:
        name: Continuous Integration
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

            - name: ci
              uses: ./.github/actions/ci

    cd:
        name: Continuous Delivery
        needs:
            - ci
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

            - name: Get short Git commit hash
              id: vars
              shell: bash
              run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

            - name: Login to Docker Hub
              uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
                  scope: 'dndmapp/dnd-mapp@push'

            - name: Set up QEMU
              uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

            - name: Build and push
              uses: docker/bake-action@82490499d2e5613fcead7e128237ef0b0ea210f7 # v7.0.0
              env:
                  TAGS: dev,sha-${{ steps.vars.outputs.sha_short }}
              with:
                  source: .
                  files: .docker/bake.hcl
                  targets: app
                  push: true
